const responseList = {
  OK: 'OK',
  CREATED: 'CREATED',
  NO_DATA: 'NO_DATA',
  REQUIRED_FIELD: 'REQUIRED_FIELD',
  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN: 'FORBIDDEN',
  NOT_FOUND: 'NOT_FOUND',
  CONFLICT: 'CONFLICT',
  INVALID_VALUES: 'INVALID_VALUES',
  ACCESS_DENIED: 'ACCESS_DENIED',
};

module.exports = responseList;
